# Generated by Django 5.0.3 on 2024-04-04 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pypeepapp", "0004_profile_profile_img"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="peep",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="peep_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
