# Generated by Django 5.0.3 on 2024-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pypeepapp", "0006_profile_facebook_link_profile_homepage_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
